### ISSUE TITLE
HDR video upload - truncated length

### ISSUE THREAD

**Issue by zmarty** [YouTubeHDR/hdr_metadata#13]
I uploaded an HDR video: https://www.youtube.com/watch?v=dg3I2DJ7C1U

The video I uploaded has 1 minute and 33 seconds. It plays correctly on Desktop (Windows 10, Chrome) in SDR.

**However**, the video manager says this video has only 11 seconds:

![Video Manager screenshot](http://i.imgur.com/xVfLAzM.png)

**Even worse**, when I play the video on my Android phone (Samsung S5), the video actually only plays for 11 seconds.

Please check why some of the transcoded streams were truncated.

Thanks!

**Comment by nbirkbeck** [comment]
Is this still happening? If so, can you please check "stats for nerds" and let me know which formats are the problematic.

**Comment by zmarty** [comment]
Support fixed it.
