### ISSUE TITLE
Support for SDR video track instead of LUT

### ISSUE THREAD

**Issue by irieger** [YouTubeHDR/hdr_metadata#4]
Hey,

is it planned to support adding the SDR version of a video as an additional video track instead of only a LUT? I like that an individual LUT is supported but often a LUT wont cover all cases of different lighting inside a movie - which is also why I prefer Dolby Vision with dynamic metadata to HDR10 (in its current standard version). Dynamic metadata (without the need for overly expensive Dolby Vision finishing) would also be a great alternative.

**Comment by YouTubeHDR** [comment]
Hi, 
Thanks for the comments. We have considered various ways to improve user experience for HDR to SDR conversion. We currently don't have plan to support uploading with additional SDR track. We may support dynamic metadata once MKV spec is extended to support it.

**Comment by irieger** [comment]
Ok, hopefully something will be standardized soon.
