### ISSUE TITLE
P3: Editing the soundtrack of an HDR video with YouTube web interface yields artifacts

### ISSUE THREAD

**Issue by zmarty** [YouTubeHDR/hdr_metadata#5]
This is a minor bug for me, but I will still list it here so you know about it. I uploaded an HDR video then I replaced its soundtrack using the YouTube remove/replace song feature. This yielded green artifacts all over the HDR video so I had to remove it completely.

**Comment by YouTubeHDR** [comment]
Could you ping me the link to the video?

**Comment by zmarty** [comment]
Try this one, since I deleted that video: https://www.youtube.com/watch?v=hefz41EcQcg

Try replacing the music with another song through the Replace Song feature.

**Comment by YouTubeHDR** [comment]
Could you replace the music from your client and send me the bad video? you may unlist the video and only send me the video id, i.e., the string after "what?v=" in video url.

**Comment by zmarty** [comment]
Here is the copy with removed audio: https://www.youtube.com/watch?v=SGWdgC4lnw0

Let's see if it will have the same issue once transcoding is done.

**Comment by zmarty** [comment]
The copy of the video has finished transcoding and it has the same issue as I reported initially. When I play it on Chrome in Windows the whole screen has green artifacts everywhere. Please check.

**Comment by YouTubeHDR** [comment]
I see. That is because video edit is not supported for HDR and 360Video for now.

**Comment by zmarty** [comment]
Then I am not so sure that this item should be closed.
