### ISSUE TITLE
P2: Increase maximum upload file size for DNxHR HQX

### ISSUE THREAD

**Issue by zmarty** [YouTubeHDR/hdr_metadata#6]
The current upload file size limit is 120GB as per: https://support.google.com/youtube/answer/71673?hl=en

However, as you probably know, DNxHR HQX takes up way more space.

Right now I am looking at a 28 minute file and it's 361GB. Obviously much more than the YouTube upload limit. A 2 hour movie would be much bigger.

I have to somehow convert the video to 10-bit H.264, which is harder than it sounds, and then upload it. All this compression and decompression is not ideal.

So if you are seriously supporting DNxHR HQX you need to increase the upload limit.

**Comment by YouTubeHDR** [comment]
Could you try using apple prores codec? The encoding bitrate for DNxHR HQX is super high.

**Comment by zmarty** [comment]
Yes I will figure something out. It's only P2 for me. Prores is not supported in DaVinci Resolve on Windows, only on Mac.

**Comment by zmarty** [comment]
A bit more information.

As per the Prores whitepaper the output bitrate for 2160p at 60 fps is 383 Megabit/sec (see page 22 here http://images.apple.com/final-cut-pro/docs/Apple_ProRes_White_Paper.pdf)

So Prores can also surpass your limit for longer videos.

**Comment by zmarty** [comment]
And that's the smallest version of Prores used for scratch, The actual Prores 422 is 1178 Mbit/sec or 1768 Mbit/sec for the high quality version. DNxHR is very similar.
