### ISSUE TITLE
Clarification on maximum brightness in nits

### ISSUE THREAD

**Issue by zmarty** [YouTubeHDR/hdr_metadata#8]
We would like to upload some HDR video that goes above 1000 nits. The official documentation recommends outputting content as ST.2084 1000 nits. Is this just a recommendation or an actual limitation?

Will uploading content at 4,000 or 10,000 nits work fine?

https://support.google.com/youtube/answer/7126552?hl=en

**Comment by nbirkbeck** [comment]
That is just a recommendation given current status of TV. HDR bits are essentially pass through. The SDR downconverted version may be poor if the color grade is too high key.
