### ISSUE TITLE
Clarification on color bit depth

### ISSUE THREAD

**Issue by zmarty** [YouTubeHDR/hdr_metadata#9]
The official documentation mentions that content can/must be in 10 bits (for H.264) or 12 bit (since you are also recommending DNxHR HQX which is 12 bit).

https://support.google.com/youtube/answer/7126552?hl=en

Can you please confirm the color depth is maintained throughout the chain and HDR content is actually served at 10 or 12 bit?

Also, when you convert HDR to SDR, I assume you convert it to 8 bit?

**Comment by nbirkbeck** [comment]
HDR is always maintained at at least 10 bit throughout the processing (transcodes are 10-bit). SDR is always 8-bit.
